const {JSDOM}=require('jsdom');
const fs=require('fs'),assert=require('node:assert/strict'),vm=require('node:vm');
const root=require('node:path').resolve(__dirname,fs.existsSync(require('node:path').resolve(__dirname,'../dist/index.html'))?'../dist':'..')+'/';
const dom=new JSDOM(fs.readFileSync(root+'index.html','utf8'),{url:'https://prototype.test/#note',runScripts:'outside-only',pretendToBeVisual:true});
const w=dom.window,d=w.document;w.structuredClone=structuredClone;w.HTMLElement.prototype.scrollIntoView=function(){this.dataset.located='true'};
const context=dom.getInternalVMContext();vm.runInContext(fs.readFileSync(root+'phosphor-icons.js','utf8'),context);vm.runInContext(fs.readFileSync(root+'app.js','utf8'),context);
const ev=s=>vm.runInContext(s,context),click=s=>{const n=d.querySelector(s);assert(n,'missing '+s);n.click();},submit=()=>d.querySelector('form.composer').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
const pause=ms=>new Promise(r=>setTimeout(r,ms));const palmAction=async id=>{ev(`openPalmMenu('${id}')`);click('#menu-palm');await pause(580);};
const state=()=>JSON.parse(ev('JSON.stringify(data)')),last=()=>state().comments.at(-1),messages=kind=>state().notifications.filter(n=>n.kind===kind);
(async()=>{
// A publishes from the real DOM composer, toggle defaults off.
click('[data-action="compose"]');assert(!d.querySelector('#leave-palm').checked);assert(!d.querySelector('#palm-help'));click('#leave-palm');assert(!d.querySelector('#palm-help'));assert.equal(d.querySelector('#comment-text').value,'有没有也喜欢一个人去攀岩的？最近刚开始，想交流一下新手线路～');submit();
const invitation=last().id;assert.deepEqual(last().palm.participants,[]);assert(d.querySelector('#palm-'+invitation).textContent.includes('已邀请击掌'));assert.equal(d.querySelector('#comment-'+invitation+' .author-badge'),null);
// B joins once, local animation and count, ordinary like/reply preserved.
click('[data-role="qing"]');await palmAction(invitation);assert.deepEqual(state().comments.at(-1).palm.participants,['qing']);assert.equal(messages('palm').length,1);assert.equal(d.querySelectorAll('#palm-'+invitation+' .palm-avatar-stack img').length,1);assert(d.querySelector('#palm-'+invitation+' .palm-avatar-stack img').src.endsWith('/assets/qing.jpg'));assert(!d.querySelector('.palm-collision'));assert(d.querySelector('#palm-'+invitation).textContent.includes('已击掌'));click(`#comment-${invitation} [data-action="comment-like"]`);assert(state().comments.at(-1).likedBy.includes('qing'));
// A finds aggregated notification and thumb locates root.
click('[data-role="lin"]');click('[data-jump="messages"]');click('[data-page="likes"]');assert(d.querySelector('#app').textContent.includes('阿青向你击了个掌'));const notice=messages('palm')[0].id;click(`[data-notification="${notice}"] .note-thumb`);assert.equal(ev('page.name'),'note');assert.equal(d.querySelector('#comment-'+invitation).dataset.located,'true');click(`#palm-${invitation} [data-action="participants"]`);assert(d.querySelector('#editor-root').textContent.includes('阿青'));click('#respond-participants');
assert(d.querySelector('#notify-palm').checked);assert(d.querySelector('#editor-root .composer-overlay form.composer'));assert(d.querySelector('.group-response-composer'));assert.equal(d.querySelector('.response-recipients>span').textContent,'回应给：');assert(!d.querySelector('#cancel-editor'));assert(!d.querySelector('.composer-head'));assert(d.querySelector('.response-footer #send-comment'));assert.equal(d.querySelector('#send-comment').textContent,'回应大家');assert.equal(d.querySelector('#comment-text').value,'原来这么多同好！我周六下午准备再去，回来给大家分享几条适合新手的线路～');submit();const response=last().id;assert.deepEqual(last().palmNotified,['qing']);assert.equal(last().parent,invitation);assert.equal(messages('palm-response').length,1);assert.equal(state().comments.find(c=>c.id===invitation).palm.status,'open');
// B receives public response, row click locates nested reply, replies and A receives ordinary message.
click('[data-role="qing"]');click('[data-jump="messages"]');click('[data-page="comments"]');assert(d.querySelector('#app').textContent.includes('小林回应了你参与的评论'));const responseNotice=messages('palm-response')[0].id;const row=d.querySelector(`[data-notification="${responseNotice}"]`);assert(row.textContent.includes('原来这么多同好'));assert(row.querySelector('.quote').textContent.includes('一个人去攀岩'));click(`[data-notification="${responseNotice}"]`);assert.equal(d.querySelector('#comment-'+response).dataset.located,'true');click(`#comment-${response} [data-action="reply"]`);d.querySelector('#comment-text').value='看到了，谢谢分享！';d.querySelector('#comment-text').dispatchEvent(new w.Event('input'));submit();const reply=last().id;assert(messages('reply').some(n=>n.commentId===reply&&n.recipient==='lin'));
// Cancel stops future reminder; late rejoin receives no history.
await palmAction(invitation);assert.deepEqual(state().comments.find(c=>c.id===invitation).palm.participants,[]);click('[data-role="lin"]');click(`#comment-${invitation} [data-action="reply"]`);assert(!d.querySelector('#notify-palm'));submit();assert.equal(messages('palm-response').length,1);click('[data-role="qing"]');await palmAction(invitation);assert.equal(messages('palm-response').length,1);assert(d.querySelector('#comment-'+response));
// Unchecked notification publishes only; synthetic second reader checks aggregation.
click('[data-role="lin"]');click(`#comment-${invitation} [data-action="reply"]`);assert(!d.querySelector('#notify-palm').checked);submit();assert.equal(messages('palm-response').length,1);
ev(`role='cheng';togglePalm('${invitation}');role='lin';render();`);assert.equal(messages('palm')[0].actors.length,2);assert.equal(d.querySelectorAll('#palm-'+invitation+' .palm-avatar-stack img').length,2);ev("navigate('likes')");assert(d.querySelector('#app').textContent.includes('阿橙等2人向你击了个掌'));ev(`navigate('note',{target:'${invitation}'})`);
// End prevents new joins/reminders, preserves all replies.
d.querySelector(`#comment-${invitation} [data-comment-menu]`).dispatchEvent(new w.Event('contextmenu',{bubbles:true,cancelable:true}));click('#toggle-palm-type');assert.equal(state().comments.find(c=>c.id===invitation).palm.status,'closed');const before=messages('palm-response').length;click(`#comment-${invitation} [data-action="reply"]`);assert(!d.querySelector('#notify-palm'));submit();assert.equal(messages('palm-response').length,before);ev(`role='qing';render();`);assert(!d.querySelector(`#palm-${invitation} .palm-cancel`));assert.equal(ev(`togglePalm('${invitation}',{joinOnly:true})`),false);
// Delete hides root and descendants but leaves old notices as tombstones, safely opens note.
ev("role='lin';render()");d.querySelector(`#comment-${invitation} [data-comment-menu]`).dispatchEvent(new w.Event('contextmenu',{bubbles:true,cancelable:true}));click('#delete-palm');assert(!d.querySelector('#comment-'+invitation));assert(!d.querySelector('#comment-'+response));ev("role='qing';navigate('comments')");assert(d.querySelector(`[data-notification="${responseNotice}"]`).textContent.includes('原评论已删除'));click(`[data-notification="${responseNotice}"]`);assert.equal(ev('page.name'),'note');assert(d.querySelector('#toast').textContent.includes('原评论已删除'));
// Normal composer still defaults off and creates a normal comment; persistence restores shared state.
click('[data-action="compose"]');assert(!d.querySelector('#leave-palm').checked);d.querySelector('#comment-text').value='<普通评论>';submit();assert(!last().palm);assert(d.querySelector('#comment-'+last().id).textContent.includes('<普通评论>'));assert(!d.querySelector('#comment-'+last().id+' 普通评论'));assert.equal(JSON.parse(w.localStorage.getItem('rednote-community-base-v1')).comments.at(-1).text,'<普通评论>');
// Original private chat remains shared between roles.
ev("navigate('chat',{peer:'lin'})");ev("sendMessage('聊天保持原样')");ev("switchRole('lin')");assert(d.querySelector('#app').textContent.includes('聊天保持原样'));
console.log('PASS: complete A → B → A → B → A DOM flow, cancellation, late join, no reminder, aggregation, ending, deletion, ordinary comment/like/reply/chat and persistence');w.close();

})().catch(e=>{console.error(e);w.close();process.exitCode=1});
